declare const gulp: any;
declare const imagemin: any;
declare const svgmin: any;
declare const jpeg: any;
declare const optipng: any;
declare const gifsicle: any;
declare const path: any;
declare const resolvePath: any;
declare const fs: any;
declare const readFile: any;
declare const readdir: any;
declare const getPixels: any;
declare const imageHash: any;
declare const performance: any;
declare const crypto: any;
declare class CompressImagesAll {
    private cacheDirectory;
    private source;
    private destination;
    private extensions;
    private count;
    private root;
    private directories;
    private globalImagesCount;
    private cachedHashChecksums;
    private cachedHashChecksumsTemp;
    private removeUnusedFiles;
    private displayLogging;
    private cachedFilename;
    private timeStart;
    private timeEnd;
    private removeTargetIfExists;
    private bits;
    private hash;
    constructor();
    setSource(source?: string): CompressImagesAll;
    getSource(): string;
    setDestination(destination?: string): CompressImagesAll;
    getDestination(): string;
    setCachedDirectory(directory: string): CompressImagesAll;
    getCachedDirectory(): string;
    setExtensions(extensions?: never[]): CompressImagesAll;
    getExtensions(): any[];
    setRemoveUnusedFiles(removeUnusedFiles: boolean): CompressImagesAll;
    getRemoveUnusedFiles(): boolean;
    setDisplayLogging(displayLogging: boolean): CompressImagesAll;
    getDisplayLogging(): boolean;
    setCacheFilename(cachedFilename: string): CompressImagesAll;
    getCacheFilename(): string;
    setRemoveTargetIfExists(removeTargetIfExists: boolean): CompressImagesAll;
    getRemoveTargetIfExists(): boolean;
    setBits(bits: number): CompressImagesAll;
    getBits(): number;
    setHash(hash: string): CompressImagesAll;
    getHash(): string;
    progressSingleDirectory(directory: string, singleSourcePath: {
        cachedPath: string;
        files: string[];
        count: number;
    }): Promise<unknown>;
    processSingleImageWithCacheDirectory(source: string, destination: string, cachedPath: string): Promise<unknown>;
    processSingleImage(source: string, destination: string): Promise<unknown>;
    createCachedDirectory(): void;
    logger(message: string): void;
    Async(p: any): Promise<boolean>;
    makeDir(destination?: string): Promise<boolean>;
    getFiles(dir: string, files?: {}): Promise<{
        [direcotry: string]: [files: string[], count: number];
    }>;
    getChecksums(): Promise<{
        [directory: string]: string;
    }>;
    saveFileWithChecksums(cachedHashChecksums: {
        [key: string]: any;
    }): Promise<boolean>;
    fileExists(filepath: string): boolean;
    calculateHash(filePath: string): Promise<string>;
    compress(): Promise<unknown>;
    start(): Promise<unknown>;
}
