declare const gulp: any;
declare const imagemin: any;
declare const optipng: any;
declare const gifsicle: any;
declare const svg: any;
declare const path: any;
declare const fs: any;
declare const imageHash: any;
declare const jpeg: any;
declare const webp: any;
declare const md5: any;
declare const cache: any;
declare const avif: any;
declare const resolvePath: any;
declare const readdir: any;
declare const performance: any;
declare class CompressImagesAll {
    private cacheDirectory;
    private source;
    private destination;
    private extensions;
    private count;
    private root;
    private directories;
    private globalImagesCount;
    private max;
    private cachedHashChecksums;
    private cachedHashChecksumsTemp;
    private removeUnusedFiles;
    private displayLogging;
    private cachedFilename;
    private timeStart;
    private timeEnd;
    private removeTargetIfExists;
    private algorithmBits;
    private algorithmHash;
    private generateWebp;
    private generateAvif;
    private loggingCallback;
    private cacheAlgorithm;
    private webpOptions;
    private avifOptions;
    private clearGulpCache;
    constructor();
    setSource(source?: string): CompressImagesAll;
    getSource(): string;
    setDestination(destination?: string): CompressImagesAll;
    getDestination(): string;
    setCachedDirectory(directory: string): CompressImagesAll;
    getCachedDirectory(): string;
    setExtensions(extensions?: never[]): CompressImagesAll;
    getExtensions(): any[];
    setRemoveUnusedFiles(removeUnusedFiles: boolean): CompressImagesAll;
    getRemoveUnusedFiles(): boolean;
    setDisplayLogging(displayLogging: boolean): CompressImagesAll;
    getDisplayLogging(): boolean;
    setCacheFilename(cachedFilename: string): CompressImagesAll;
    getCacheFilename(): string;
    setRemoveTargetIfExists(removeTargetIfExists: boolean): CompressImagesAll;
    getRemoveTargetIfExists(): boolean;
    setAlgorithmBits(algorithmBits: number): CompressImagesAll;
    getAlgorithmBits(): number;
    setAlgorithmHash(algorithmHash: string): CompressImagesAll;
    getAlgorithmHash(): string;
    setGenerateWebp(generateWebp: boolean): CompressImagesAll;
    getGenerateWebp(): boolean;
    setGenerateAvif(generateAvif: boolean): CompressImagesAll;
    getGenerateAvif(): boolean;
    setLoggingCallback(loggingCallback: any): CompressImagesAll;
    getLoggingCallback(): boolean;
    setCacheAlgorithm(cacheAlgorithm: string): CompressImagesAll;
    getCacheAlgorithm(): string;
    setWebpOptions(webpOptions: {
        [key: string]: any;
    }): CompressImagesAll;
    getWebpOptions(): {
        [key: string]: any;
    };
    setAvifOptions(avifOptions: {
        [key: string]: any;
    }): CompressImagesAll;
    getAvifOptions(): {
        [key: string]: any;
    };
    setClearGulpCache(clearGulpCache: boolean): CompressImagesAll;
    getClearGulpCache(): boolean;
    progressSingleDirectory(directory: string, singleSourcePath: {
        cachedPath: string;
        files: string[];
        count: number;
    }): Promise<unknown>;
    processSingleImageWithCacheDirectory(source: string, destination: string, cachedPath: string): Promise<unknown>;
    processSingleImageWithCacheDirectoryGulpCache(source: string, destination: string, cachedPath: string): Promise<unknown>;
    processSingleImage(source: string, destination: string): Promise<unknown>;
    createCachedDirectory(): void;
    logger(message: string): void;
    Async(p: any): Promise<boolean>;
    makeDir(destination?: string): Promise<boolean>;
    getFiles(dir: string, files?: {}): Promise<{
        [direcotry: string]: [files: string[], count: number];
    }>;
    getChecksums(): Promise<{
        [directory: string]: string;
    }>;
    saveFileWithChecksums(cachedHashChecksums: {
        [key: string]: any;
    }): Promise<boolean>;
    fileExists(filepath: string): boolean;
    calculateHash(filePath: string): Promise<string>;
    compress(): Promise<unknown>;
    start(): Promise<unknown>;
}
