declare const fs: any;
declare const fsp: any;
declare const path: any;
declare const nodeCrypto: any;
declare const sharp: any;
declare const optimize: any;
declare const pLimit: any;
declare const nodePerformance: any;
declare class CompressImagesAll {
    private cacheDirectory;
    private source;
    private destination;
    private extensions;
    private count;
    private root;
    private sourceDirectoriesNames;
    private globalImagesCount;
    private max;
    private cachedHashChecksums;
    private cachedHashChecksumsTemp;
    private removeUnusedFiles;
    private displayLogging;
    private cachedFilename;
    private timeStart;
    private timeEnd;
    private removeTargetIfExists;
    private generateWebp;
    private generateAvif;
    private loggingCallback;
    private webpOptions;
    private avifOptions;
    private copyNotImages;
    constructor();
    setCopyNotImages(copyNotImages?: boolean): CompressImagesAll;
    getCopyNotImages(): boolean;
    setSource(source?: string): CompressImagesAll;
    getSource(): string;
    setDestination(destination?: string): CompressImagesAll;
    getDestination(): string;
    setCachedDirectory(directory: string): CompressImagesAll;
    getCachedDirectory(): string;
    setExtensions(extensions?: never[]): CompressImagesAll;
    getExtensions(): any[];
    setRemoveUnusedFiles(removeUnusedFiles: boolean): CompressImagesAll;
    getRemoveUnusedFiles(): boolean;
    setDisplayLogging(displayLogging: boolean): CompressImagesAll;
    getDisplayLogging(): boolean;
    setCacheFilename(cachedFilename: string): CompressImagesAll;
    getCacheFilename(): string;
    setRemoveTargetIfExists(removeTargetIfExists: boolean): CompressImagesAll;
    getRemoveTargetIfExists(): boolean;
    setGenerateWebp(generateWebp: boolean): CompressImagesAll;
    getGenerateWebp(): boolean;
    setGenerateAvif(generateAvif: boolean): CompressImagesAll;
    getGenerateAvif(): boolean;
    setLoggingCallback(loggingCallback: any): CompressImagesAll;
    getLoggingCallback(): boolean;
    setWebpOptions(webpOptions: {
        [key: string]: any;
    }): CompressImagesAll;
    getWebpOptions(): {
        [key: string]: any;
    };
    setAvifOptions(avifOptions: {
        [key: string]: any;
    }): CompressImagesAll;
    getAvifOptions(): {
        [key: string]: any;
    };
    logger(message: string): void;
    makeDir(destination?: string): Promise<boolean>;
    fileExists(filepath: string): boolean;
    getFileExtension(source: string): string;
    getSourceFiles(dir: string, files?: any): Promise<any>;
    scanFiles(dir: string, fileList?: string[]): Promise<string[]>;
    calculateHash(filePath: string): Promise<string>;
    getChecksums(): Promise<{
        [key: string]: any;
    }>;
    saveChecksums(data: {
        [key: string]: any;
    }): Promise<void>;
    start(): Promise<unknown>;
    processImage(sourcePath: string): Promise<void>;
    optimizeRaster(source: string, dest: string, ext: string): Promise<void>;
    convertToWebp(source: string, dest: string): Promise<void>;
    convertToAvif(source: string, dest: string): Promise<void>;
    optimizeSvg(source: string, dest: string): Promise<void>;
    changeExt(filename: string, newExt: string): string;
    cleanupCache(): Promise<void>;
    safeDelete(filePath: string): Promise<void>;
}
